# Generated by Django 4.2.22 on 2025-07-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_adminassistantmodel_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingboost',
            name='auto_repost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingboost',
            name='auto_repost_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
