# Generated by Django 5.2.4 on 2025-07-18 16:40

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_userprofile_clerk_user_id_escrowpayment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to=marketplace.models.listing_image_path),
        ),
    ]
