# Generated by Django 5.2.4 on 2025-07-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_listingimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='clerk_user_id',
        ),
    ]
