# Generated by Django 5.2.5 on 2025-09-03 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_remove_clerk_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['expires_at'], name='marketplace_expires_9c9d32_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location_verified'], name='marketplace_locatio_9c28d7_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_premium', 'created_at'], name='marketplace_is_prem_4535f9_idx'),
        ),
    ]
