# Generated by Django 5.2.4 on 2025-07-19 07:16

import django.db.models.deletion
from django.db import migrations, models
from pgvector.django import VectorField


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_make_location_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_embedding', VectorField(dimensions=1536)),
                ('description_embedding', VectorField(dimensions=1536)),
                ('combined_embedding', VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='marketplace.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['listing'], name='marketplace_listing_2eab9d_idx')],
            },
        ),
    ]
