# Generated by Django 5.2.4 on 2025-07-20 08:27

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slugs for existing listings"""
    Listing = apps.get_model('marketplace', 'Listing')
    for listing in Listing.objects.all():
        if not listing.slug:
            base_slug = slugify(listing.title)
            slug = base_slug
            counter = 1
            
            # Ensure unique slug
            while Listing.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            listing.slug = slug
            listing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_listingembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(max_length=200, blank=True, null=True),
        ),
        migrations.RunPython(populate_slugs),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
