# Generated by Django 5.2.4 on 2025-07-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_add_slug_to_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
