# Generated by Django 5.2.5 on 2025-09-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_message_content_message_mcp_tools_used_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Conversation', max_length=100),
        ),
    ]
